export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const SAVE_CUSTOMER = 'SAVE_CUSTOMER';
export const FETCH_CUSTOMER = 'FETCH_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
